### ISSUE TITLE
so what version of dockerize does this orb use?

### ISSUE THREAD

**Issue by simkimsia** [ganta/dockerize-orb#14]
I understand the latest version is 0.6.1 https://github.com/jwilder/dockerize/releases/

but i cannot tell from the source code here which dockerize version is being used in this orb. can advise?

**Comment by ganta** [comment]
@simkimsia 
I apologize for the delay in my response.

This orb uses the dockerize command included in the build image and does not install the dockerize command.
It is assumed that [CircleCI convenience image](https://circleci.com/developer/images) will be used.

For example, in [cimg/base](https://circleci.com/developer/images/image/cimg/base):2022.01, dockerize version 0.6.1 is installed.

```
$ docker run --rm cimg/base:2022.01 dockerize --version
v0.6.1
```
